### ISSUE TITLE
Python or Andoid alternative

### ISSUE THREAD

**Issue by KapilRakh** [gaborbata/todo#3]
Do you have any plans to create an Andoid app? Alternatively, please create a Python version of the ruby code. I can run that using DroidVim on Android.

**Comment by gaborbata** [comment]
Hey @KapilRakh, I have no plans/capacity to port the application to Android/Python.

For creating an Android app you may try JRuby/Ruboto, or embed the JavaScript version in an application wrapper.

If terminal support is enough, Termux could run Ruby scripts (and also JavaScript) without any issues on Android.
